default_language_version:
  python: python3.9

default_stages: [commit, push]

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.252'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: no-commit-to-branch
        name: Don't commit to main or master branch
        description: Prevent the user from committing directly to the primary branch.

    # verify that pyproject.toml is well formed
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.12.1
    hooks:
      - id: validate-pyproject
        name: Validate syntax of pyproject.toml
        description: Verify that pyproject.toml adheres to the established schema.
  - repo: https://github.com/pdm-project/pdm
    rev: 2.4.6
    hooks:
      - id: pdm-lock-check
